version: "3.3"

services:
  bot:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/service/logs/
    ports:
      - "61616:61616"
      - "80:9000"